trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      #vmImage: windows-latest
      name: 'VenuAgent'
    steps:
    - task: CmdLine@2
      displayName: Run a one-line script
      inputs:
        script: echo Hello, world!
    - task: CmdLine@2
      displayName: Run a multi-line script
      inputs:
        script: >
          echo Add other tasks to build, test, and deploy your project.

          echo See https://aka.ms/yaml
    - task: katalonTask@0
      inputs:
        version: 7.6.2
        executeArgs: katalonc -noSplash  -projectPath="d:/a/1/s/Katalonrepo.prj" -retry=0 -testSuitePath="Test Suites/LoginSuite" -executionProfile="default" -browserType="Firefox" -apiKey="f0303d1f-0368-40ee-bc2c-83b87a7d925b" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY
    - task: ivang7.allure-test-reports.allure-generate.AllureGenerate@1
      displayName: Generate Allure Report