# Starter pipeline

trigger:
- master
 
pool:
  #vmImage: 'windows-latest'
  name: 'Default'

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'
 
- script: |
    echo "Add other tasks to build, test, and deploy your project."
    echo "See https://aka.ms/yaml"
  displayName: 'Run a multi-line script'

##katalonc -noSplash -runMode=console -projectPath="C:\Users\venudhar.c\git\Katalonrepo\Katalonrepo.prj" -retry=0 -testSuitePath="Test Suites/LoginSuite" -executionProfile="default" -browserType="Chrome" -apiKey="f0303d1f-0368-40ee-bc2c-83b87a7d925b" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true

 
- task: katalonTask@0
  inputs:
    version: '7.6.2'
    executeArgs: 'katalonc -noSplash  -projectPath="d:/a/1/s/Katalonrepo.prj" -retry=0 -testSuitePath="Test Suites/LoginSuite" -executionProfile="default" -browserType="Firefox" -apiKey="f0303d1f-0368-40ee-bc2c-83b87a7d925b" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
- task: ivang7.allure-test-reports.allure-generate.AllureGenerate@1
  displayName: 'Generate Allure Report'